### ISSUE TITLE
  went wrong :-(

### ISSUE THREAD

**Issue by spellerised3791** [jenspfahl/ANOTHERpass#31] opened 2022-11-13 03:28 UTC
First, I like your app a lot, I started using it on my pixel 3a, it worked great.
Then I changed phones for a Asus Zenfone 9, I imported the vault and it has been working great for like a day, then I try to login with my pin and tells me there was a bug after reading my pin.

So I clear the data, and import it back again, but this time after importing and putting the Master Key says something went wrong and won't restore the vault.

The problem goes away when I restart my Zenfone but comes back again after like 3 openins of the vault.

Any help?

************ CAUSE OF ERROR ************

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	... 1 more
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException(KeyStoreCryptoOperationUtils.java:128)
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:154)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:339)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:171)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2985)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1144)
	at javax.crypto.Cipher.init(Cipher.java:1085)
	at de.jepfa.yapm.service.secret.SecretService.encryptData(SecretService.kt:201)
	at de.jepfa.yapm.service.secret.SecretService.encryptPassword(SecretService.kt:165)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$onViewCreated$3$3.invoke(LoginEnterPinFragment.kt:131)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$onViewCreated$3$3.invoke(LoginEnterPinFragment.kt:126)
	at de.jepfa.yapm.service.secret.MasterPasswordService.decryptWithBiometrics(MasterPasswordService.kt:226)
	at de.jepfa.yapm.service.secret.MasterPasswordService.getMasterPasswordFromStore(MasterPasswordService.kt:67)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.onViewCreated$lambda-3(LoginEnterPinFragment.kt:126)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.$r8$lambda$2L5oUcZAgJNXJDAtleYP0VvHNWg(Unknown Source:0)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:8)
	at android.view.View.performClick(View.java:7475)
	at android.view.View.performClickInternal(View.java:7452)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28834)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:241)
	at android.os.Looper.loop(Looper.java:358)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	... 3 more

************ APP INFORMATION ***********
Version: 1.7.2_rc
Version Code: 107002
Database Version: 5
Vault Version: 2
Vault Cipher: AES_128
Build Timestamp: Oct 31, 2022 9:04:42 PM
Build Type: release

************ DEVICE INFORMATION ***********
Brand: asus
Manufacturer: asus
Device: ASUS_AI2202
Model: ASUS_AI2202
Product: JP_AI2202
Hardware: qcom
OS Build Id: SKQ1.220406.001
NFC available: true
NFC enabled: true
Has StrongBox support: false
Has biometrics support: true
Is fingerprint enroled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Overlay dialog granted: true
Camera granted: false
Biometric granted: true

************ FIRMWARE ************
SDK: 32
Release: 12
Incremental: 32.2050.2050.29
Codename: REL
Security patch: 2022-10-01

**Comment by jenspfahl** [comment] 2022-11-13 13:00
Hey and sorry for this misbehaviour. 
Have you always unlocked the master password with your biometric/fingerprint shortly before this error occured? Or does the error also occur without doing biometric scanning? 
If it is related to biometrics you could either remove your fingerprints from the phone and enrol new ones or disable biometrics for the stored master password in Settings/Security/"Authorize stored master passwords with biometric".
If it happens again please send me the cause of error again, especially if it is not related to biometrics. Thanks.

**Comment by UserNameM3** [comment] 2022-11-27 19:17
Something similar happened to me. On both of my phones (one is Xiaomi other one Samsung) it gives the same error forcing me to enter master password. Even after entering it, it can't save the master password to the device (error Cannot authorize biometric).

**Comment by jenspfahl** [comment] 2022-11-28 11:08
@UserNameM3  have you tried to disable biometrics for Master Password in Settings/Security? Does it work then? The master password is still stored in an encrypted way on the device and can only be accessed by the app (unless your device is rooted).
I am still figuring out why it's not working and I would appreciate more error logs. Thanks!

**Comment by UserNameM3** [comment] 2022-11-28 11:20
@jenspfahl Yes I did, there's no problem in storing the master password, it just doesn't work with biometric as a verification.

**Comment by jenspfahl** [comment] 2022-11-28 11:28
Alright, thanks for clarification. I will try to fix this.

**Comment by jenspfahl** [comment] 2023-06-13 18:49
Another user had a similar issue and found out that this happens when no screen lock is configured. A screen lock is kind of required to authenticate the device user to access the internal key storage. If this issue is still relevant this could be the cause.

**Comment by UserNameM3** [comment] 2023-06-15 00:19
Well that sounds quite odd as I do have pin as well as fingerprint unlock setup on both affected devices. Only way I can reproduce the issue is by changing fingerprint, but that's to be expected (for security reasons) but after one succesful sign in, it works again. Tbh I don't know if it's still relevant as I haven't encountered this issue in quite some time.

**Comment by jenspfahl** [comment] 2023-07-03 16:12
Should be fixed with version 1.8.0

**Closed by jenspfahl** 2023-07-03 16:12 UTC
