### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by ruafelianna** [jenspfahl/ANOTHERpass#38] opened 2023-01-26 22:14 UTC
************ CAUSE OF ERROR ************

java.lang.NoSuchMethodError: No virtual method getHintIdEntry()Ljava/lang/String; in class Landroid/app/assist/AssistStructure$ViewNode; or its super classes (declaration of 'android.app.assist.AssistStructure$ViewNode' appears in /system/framework/framework.jar)
	at de.jepfa.yapm.service.autofill.ResponseFiller.inspectNodeAttributes(ResponseFiller.kt:491)
	at de.jepfa.yapm.service.autofill.ResponseFiller.identifyFields(ResponseFiller.kt:458)
	at de.jepfa.yapm.service.autofill.ResponseFiller.identifyFields(ResponseFiller.kt:433)
	at de.jepfa.yapm.service.autofill.ResponseFiller.createFillResponse(ResponseFiller.kt:169)
	at de.jepfa.yapm.service.autofill.ResponseFiller.createFillResponse$default(ResponseFiller.kt:118)
	at de.jepfa.yapm.service.autofill.CredentialFillService.onFillRequest(CredentialFillService.kt:30)
	at android.service.autofill.-$$Lambda$I0gCKFrBTO70VZfSZTq2fj-wyG8.accept(Unknown Source:8)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:300)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8676)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

************ APP INFORMATION ***********
Version: 1.7.2
Version Code: 107002
Database Version: 5
Vault Version: 2
Vault Cipher: AES_256
Build Timestamp: 17 дек. 2022 г. 04:12:01
Build Type: release

************ DEVICE INFORMATION ***********
Brand: HONOR
Manufacturer: HUAWEI
Device: HWBKL
Model: BKL-L09
Product: BKL-L09
Hardware: kirin970
OS Build Id: HUAWEIBKL-L09S
NFC available: true
NFC enabled: false
Has StrongBox support: false
Has biometrics support: true
Is fingerprint enroled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Overlay dialog granted: true
Camera granted: false
Biometric granted: true

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.177C10
Codename: REL
Security patch: 2020-04-01

**Comment by ruafelianna** [comment] 2023-01-26 22:16
It happened after I set this app as an app for autofill in my android's settings and opened the site to autofill my credentials.

**Comment by jenspfahl** [comment] 2023-01-27 11:09
I found the cause. Gonna fix this soon. Thanks for reporting it !

**Comment by jenspfahl** [comment] 2023-02-05 19:13
Fixed with 1.7.3

**Closed** 2023-02-05 19:12 UTC
